#!/usr/bin/env bash
# Build LFortran with the native xeus Jupyter kernel and install it, together
# with its kernelspec, into a self-contained prefix under build-lab-native/.
#
# Driven by `pixi run lab-native` (see pixi.toml); `jupyter lab` then finds the
# "Fortran" kernel through JUPYTER_PATH pointing at install/share/jupyter.
#
# The install is a real one because the kernelspec generated by CMake stores an
# absolute path to the installed binary, and the kernel resolves its runtime
# .mod files relative to that binary.
#
# The tree is kept separate from the in-source build made by build1.sh: XEUS
# needs RTTI, which is a global compile option, so sharing a CMake cache with a
# non-XEUS build would force a full rebuild on every switch.

set -e
set -x

# The installed binary must keep finding libxeus-zmq and friends in the pixi
# environment: CMake strips the build-tree RPATH on install, so an explicit
# install RPATH is set below.
BUILD_DIR=${BUILD_DIR:-build-lab-native}
BUILD_TYPE=${BUILD_TYPE:-Debug}
PREFIX="$(cd "$(dirname "$0")" && pwd)/$BUILD_DIR/install"

# LFORTRAN_BUILD_ALL=yes runs build0.sh (parser, ASDL headers) at configure time.
cmake -S . -B "$BUILD_DIR" -G Ninja \
    -DCMAKE_BUILD_TYPE="$BUILD_TYPE" \
    -DWITH_LLVM=yes \
    -DWITH_XEUS=yes \
    -DLFORTRAN_BUILD_ALL=yes \
    -DWITH_STACKTRACE=no \
    -DWITH_RUNTIME_STACKTRACE=no \
    -DWITH_LSP=no \
    -DUSE_DYNAMIC_ZSTD=no \
    -DCMAKE_PREFIX_PATH="$CMAKE_PREFIX_PATH_LFORTRAN;$CONDA_PREFIX" \
    -DCMAKE_INSTALL_PREFIX="$PREFIX" \
    -DCMAKE_INSTALL_LIBDIR=share/lfortran/lib \
    -DCMAKE_INSTALL_RPATH="$CONDA_PREFIX/lib" \
    -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=ON \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

cmake --build "$BUILD_DIR" --target install
