[project]
name = "lfortran"
version = "0.42.0"
description = "Modern interactive LLVM-based Fortran compiler"
authors = ["LFortran Maintainers <lfortran@groups.io>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "win-64", "linux-64"]

# feature.default.tasks
[tasks]
start = "src/bin/lfortran"
clean = "git clean -dfx -e '.pixi'"

[feature.test.tasks]
test = "cmake --build . --parallel --target test && ./run_tests.py && cd integration_tests && ./run_tests.py -j16"

[feature.llvm11.host-dependencies]
llvmdev = "11.1.0"

[feature.llvm19.host-dependencies]
llvmdev = "19.1.4"

# Dependencies to build the project to be installed for the target architecture.
# host == target
[feature.build.host-dependencies]
pytest = "8.1.1"
jupyter = "1.0.0"
xeus = "5.1.0"
xeus-zmq = "3.0.0"
nlohmann_json = "3.11.3"
jupyter_kernel_test = "0.7.0"
xonsh = "0.16.0"
numpy = "1.26.4"
rapidjson = "1.1.0"
zlib = "*"
zstd-static = ">=1.5.6,<2"

# Dependencies to build the project to be installed on the build machine.
# feature.default.build-dependencies
[build-dependencies]
python = "3.12"

[feature.build.build-dependencies]
python = "3.12"
cmake = "3.29.1"
ninja = "1.11.1"
#cxx-compiler = "*"
re2c = "3.1"

[feature.test.build-dependencies]
python = "3.12"
toml = "0.10.2"
cmake = "3.29.1"
ninja = "1.11.1"

[feature.build.target.unix.build-dependencies]
bison = "3.4"

[feature.build.target.win.build-dependencies]
m2-bison = "3.0.4"

[feature.build.tasks]
build = { cmd = "bash ./build1.sh", env = { CMAKE_PREFIX_PATH_LFORTRAN = "$PIXI_PROJECT_ROOT/.pixi/envs/build/" }}

[environments]
build = {features = ["llvm11", "build"]}
llvm11 = {features = ["llvm11", "build"]}
llvm19 = {features = ["llvm19", "build"]}
test = {features = ["test"]}
