[project]
name = "lfortran"
version = "0.42.0"
description = "Modern interactive LLVM-based Fortran compiler"
authors = ["LFortran Maintainers <lfortran@groups.io>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "win-64", "linux-64"]

[tasks]
start = "src/bin/lfortran"
test = "cmake --build . --parallel --target test && ./run_tests.py && cd integration_tests && ./run_tests.py -j16"
clean = "git clean -dfx -e '.pixi'"

[feature.host.tasks]
# an empty task to make sure the dependencies are installed
setup = "echo 'host dependencies installed'"

[host-dependencies]
llvmdev = "11.1.0"
toml = "0.10.2"
pytest = "8.1.1"
jupyter = "1.0.0"
xeus = "5.1.0"
xeus-zmq = "3.0.0"
nlohmann_json = "3.11.3"
jupyter_kernel_test = "0.7.0"
xonsh = "0.16.0"
numpy = "1.26.4"
rapidjson = "1.1.0"
zlib = "*"
zstd-static = ">=1.5.6,<2"

[build-dependencies]
python = "3.12"
cmake = "3.29.1"
ninja = "1.11.1"
#cxx-compiler = "*"
re2c = "3.1"

[target.unix.build-dependencies]
bison = "3.4"

[target.win.build-dependencies]
m2-bison = "3.0.4"

[feature.build.tasks]
build = { cmd = "bash ./build1.sh", env = { CMAKE_PREFIX_PATH_LFORTRAN = "$PIXI_PROJECT_ROOT/.pixi/envs/host/" }, depends-on = ["setup"]}

[environments]
build = ["build"]
host = ["host"]
