/-
Memory safety of the translated `sparse.f90`: no array is ever indexed out
of bounds.

* `csr_matvec_in_bounds`: `csr_matvec` is safe for *every* valid CSR matrix.
* `coo2csr_valid`: `coo2csr` is safe for every valid COO matrix, and it
  produces a valid CSR matrix.
* `tridiag_coo_valid`: `tridiag_coo` is safe and produces a valid COO matrix.
* `main_no_out_of_bounds`: `program sparse` never indexes out of bounds.

The verification conditions are generated by `mvcgen`. Every `fget` / `fset`
produces one bounds goal.
-/
import SparseLean.Sparse

open Std.Do

set_option mvcgen.warning false

namespace Fortran.Sparse

/-! ## Valid CSR matrices -/

/-- `(row_ptr, col_ind, val)` is a valid `n × n` CSR matrix with `nnz` entries:
the arrays have their declared sizes, `row_ptr` starts at `1`, ends at
`nnz + 1` and is non-decreasing, and every column index stored in a row
`i` (positions `row_ptr(i), ..., row_ptr(i+1) - 1`) is in `1..n`. -/
def ValidCSR (n nnz : ℤ) (row_ptr col_ind : Array ℤ) (val : Array ℚ) : Prop :=
  0 ≤ n ∧ (row_ptr.size : ℤ) = n + 1 ∧ (col_ind.size : ℤ) = nnz ∧ (val.size : ℤ) = nnz ∧
  fval row_ptr 1 = 1 ∧ fval row_ptr (n + 1) = nnz + 1 ∧
  (∀ i, 1 ≤ i → i ≤ n → fval row_ptr i ≤ fval row_ptr (i + 1)) ∧
  (∀ i, 1 ≤ i → i ≤ n → ∀ k, fval row_ptr i ≤ k → k < fval row_ptr (i + 1) →
    1 ≤ fval col_ind k ∧ fval col_ind k ≤ n)

/-- In a valid CSR matrix, `1 ≤ row_ptr(i) ≤ nnz + 1` for all `i`. -/
theorem ValidCSR.row_ptr_bounds {n nnz : ℤ} {row_ptr col_ind : Array ℤ} {val : Array ℚ}
    (hv : ValidCSR n nnz row_ptr col_ind val) :
    ∀ i, 1 ≤ i → i ≤ n + 1 → 1 ≤ fval row_ptr i ∧ fval row_ptr i ≤ nnz + 1 := by
  obtain ⟨hn, -, -, -, h1, hlast, hmono, -⟩ := hv
  have lo : ∀ m : ℕ, (m : ℤ) ≤ n → 1 ≤ fval row_ptr (m + 1) := by
    intro m
    induction m with
    | zero => intro _; simp [h1]
    | succ m ih =>
      intro hm
      have := hmono (m + 1) (by omega) (by omega)
      push_cast at *
      have := ih (by omega)
      omega
  have hi : ∀ m : ℕ, (m : ℤ) ≤ n → fval row_ptr (n + 1 - m) ≤ nnz + 1 := by
    intro m
    induction m with
    | zero => intro _; simp [hlast]
    | succ m ih =>
      intro hm
      have := hmono (n - m) (by omega) (by omega)
      rw [show n - m + 1 = n + 1 - m by ring] at this
      push_cast
      rw [show n + 1 - (m + 1) = n - m by ring]
      have := ih (by omega)
      omega
  intro i hi1 hi2
  obtain ⟨m, rfl⟩ : ∃ m : ℕ, i = m + 1 := ⟨(i - 1).toNat, by omega⟩
  obtain ⟨m', hm'⟩ : ∃ m' : ℕ, (m : ℤ) + 1 = n + 1 - m' := ⟨(n - m).toNat, by omega⟩
  exact ⟨lo m (by omega), hm' ▸ hi m' (by omega)⟩

/-! ## `csr_matvec` -/

/-- **`csr_matvec` never indexes out of bounds**, for every valid CSR matrix
and every vector `x(1:n)`. -/
theorem csr_matvec_in_bounds (n nnz : ℤ) (row_ptr col_ind : Array ℤ) (val x : Array ℚ)
    (hv : ValidCSR n nnz row_ptr col_ind val) (hx : (x.size : ℤ) = n) :
    ⦃⌜True⌝⦄ csr_matvec n nnz row_ptr col_ind val x ⦃⇓ y => ⌜(y.size : ℤ) = n⌝⦄ := by
  have hrp := hv.row_ptr_bounds
  obtain ⟨hn, hs1, hs2, hs3, -, -, -, hcol⟩ := hv
  mvcgen [csr_matvec]
  invariants
  · ⇓⟨xs, y⟩ => ⌜(y.size : ℤ) = n⌝
  · ⇓⟨xs, y⟩ => ⌜(y.size : ℤ) = n⌝
  all_goals fortran_vcs

/-- The precondition matters: for a matrix whose column index `2` is out of
range (`n = 1`), `csr_matvec` reads `x(2)` out of bounds. -/
theorem csr_matvec_invalid_col :
    csr_matvec 1 1 #[1, 2] #[2] #[1] #[1] = .error (.outOfBounds 2) := by
  rfl

/-! ## Valid COO matrices and `tridiag_coo` -/

/-- Entries `1..k` of a COO matrix have row and column indices in `1..n`. -/
def COOPrefix (n : ℤ) (row col : Array ℤ) (k : ℤ) : Prop :=
  ∀ j, 1 ≤ j → j ≤ k → 1 ≤ fval row j ∧ fval row j ≤ n ∧ 1 ≤ fval col j ∧ fval col j ≤ n

/-- `(row, col, val)` is a valid `n × n` COO matrix with `nnz` entries: the
arrays have their declared sizes and all row and column indices are in
`1..n`. -/
def ValidCOO (n nnz : ℤ) (row col : Array ℤ) (val : Array ℚ) : Prop :=
  0 ≤ n ∧ 0 ≤ nnz ∧ (row.size : ℤ) = nnz ∧ (col.size : ℤ) = nnz ∧ (val.size : ℤ) = nnz ∧
  COOPrefix n row col nnz

theorem COOPrefix.mono {n k m : ℤ} {row col : Array ℤ} (h : COOPrefix n row col k) (hm : m ≤ k) :
    COOPrefix n row col m :=
  fun j hj1 hj2 => h j hj1 (by omega)

theorem coo_init (n : ℤ) (row col : Array ℤ) : COOPrefix n row col 0 :=
  fun _ _ _ => by omega

/-- Appending one entry `(a, b)` with `1 ≤ a, b ≤ n` at position `m = k + 1`. -/
theorem coo_step {n k m a b : ℤ} {row col : Array ℤ} (h : COOPrefix n row col k)
    (hm : m = k + 1) (hr : m ≤ row.size) (hc : m ≤ col.size) (hk : 0 ≤ k)
    (ha : 1 ≤ a ∧ a ≤ n) (hb : 1 ≤ b ∧ b ≤ n) :
    COOPrefix n (fupd row m a) (fupd col m b) m := by
  intro j hj1 hj2
  rw [fval_fupd (by omega) (by omega), fval_fupd (by omega) (by omega)]
  split_ifs with hj
  · omega
  · exact h j hj1 (by omega)

/-- **`tridiag_coo` never indexes out of bounds** and returns a valid COO
matrix with `3n - 2` entries. -/
theorem tridiag_coo_valid (n : ℤ) (hn : 1 ≤ n) :
    ⦃⌜True⌝⦄ tridiag_coo n ⦃⇓ r => ⌜ValidCOO n (3 * n - 2) r.1 r.2.1 r.2.2⌝⦄ := by
  mvcgen [tridiag_coo]
  invariants
  · ⇓⟨xs, row, col, val, k⟩ => ⌜k = xs.pos ∧ (row.size : ℤ) = 3 * n - 2 ∧
      (col.size : ℤ) = 3 * n - 2 ∧ (val.size : ℤ) = 3 * n - 2 ∧ COOPrefix n row col k⌝
  · ⇓⟨xs, row, col, val, k⟩ => ⌜k = n + xs.pos ∧ (row.size : ℤ) = 3 * n - 2 ∧
      (col.size : ℤ) = 3 * n - 2 ∧ (val.size : ℤ) = 3 * n - 2 ∧ COOPrefix n row col k⌝
  · ⇓⟨xs, row, col, val, k⟩ => ⌜k = 2 * n - 1 + xs.pos ∧ (row.size : ℤ) = 3 * n - 2 ∧
      (col.size : ℤ) = 3 * n - 2 ∧ (val.size : ℤ) = 3 * n - 2 ∧ COOPrefix n row col k⌝
  all_goals fortran_vcs
  all_goals simp_all (config := { zetaDelta := true }) [falloc, ValidCOO]
  all_goals try casesm* _ ∧ _
  all_goals split_conj
  all_goals first
    | omega
    | exact coo_init _ _ _
    | (apply coo_step <;> vc_side)
    | (apply COOPrefix.mono <;> vc_side)

/-! ## `coo2csr`

The bounds check of the scatter step `col_ind(p) = col(k)` is the only
non-trivial one: it holds because row `r` owns exactly `cnt r` positions
starting at `row_ptr(r)`, and fewer than `cnt r` of them have been used
before entry `k` (which is itself in row `r`). We count with the following
functions. -/

/-- `cnt row s k` is the number of `j ∈ 1..k` with `row(j) = s`. -/
def cnt (row : Array ℤ) (s : ℤ) : ℕ → ℤ
  | 0 => 0
  | k + 1 => cnt row s k + if fval row ((k + 1 : ℕ) : ℤ) = s then 1 else 0

/-- `cntLt row s k` is the number of `j ∈ 1..k` with `row(j) < s`. -/
def cntLt (row : Array ℤ) (s : ℤ) : ℕ → ℤ
  | 0 => 0
  | k + 1 => cntLt row s k + if fval row ((k + 1 : ℕ) : ℤ) < s then 1 else 0

section Counting
variable {row : Array ℤ}

theorem cnt_nonneg (s : ℤ) (k : ℕ) : 0 ≤ cnt row s k := by
  induction k with
  | zero => simp [cnt]
  | succ k ih => simp only [cnt]; split_ifs <;> omega

theorem cnt_mono (s : ℤ) {k k' : ℕ} (h : k ≤ k') : cnt row s k ≤ cnt row s k' := by
  induction h with
  | refl => exact le_rfl
  | step _ ih => simp only [cnt]; split_ifs <;> omega

/-- If entry `k + 1 ≤ K` is in row `s`, it is one of the `cnt row s K` entries of
row `s` that have not been counted in `cnt row s k`. -/
theorem cnt_lt {s : ℤ} {k K : ℕ} (hk : k + 1 ≤ K) (hs : fval row ((k + 1 : ℕ) : ℤ) = s) :
    cnt row s k + 1 ≤ cnt row s K := by
  have := cnt_mono (row := row) s hk
  simp only [cnt, hs, if_pos] at this
  omega

theorem cntLt_nonneg (s : ℤ) (k : ℕ) : 0 ≤ cntLt row s k := by
  induction k with
  | zero => simp [cntLt]
  | succ k ih => simp only [cntLt]; split_ifs <;> omega

theorem cntLt_succ (s : ℤ) (k : ℕ) : cntLt row (s + 1) k = cntLt row s k + cnt row s k := by
  induction k with
  | zero => simp [cntLt, cnt]
  | succ k ih => simp only [cntLt, cnt, ih]; split_ifs <;> omega

theorem cntLt_mono {s s' : ℤ} (h : s ≤ s') (k : ℕ) : cntLt row s k ≤ cntLt row s' k := by
  induction k with
  | zero => simp [cntLt]
  | succ k ih => simp only [cntLt]; split_ifs <;> omega

theorem cntLt_one {k : ℕ} (h : ∀ j : ℕ, 1 ≤ j → j ≤ k → 1 ≤ fval row j) : cntLt row 1 k = 0 := by
  induction k with
  | zero => simp [cntLt]
  | succ k ih =>
    have := h (k + 1) (by omega) le_rfl
    simp only [cntLt, ih fun j hj1 hj2 => h j hj1 (by omega)]
    split_ifs <;> omega

theorem cntLt_top {n : ℤ} {k : ℕ} (h : ∀ j : ℕ, 1 ≤ j → j ≤ k → fval row j ≤ n) :
    cntLt row (n + 1) k = k := by
  induction k with
  | zero => simp [cntLt]
  | succ k ih =>
    have := h (k + 1) (by omega) le_rfl
    simp only [cntLt, ih fun j hj1 hj2 => h j hj1 (by omega)]
    split_ifs <;> push_cast <;> omega

end Counting

/-! ### Loop invariants of `coo2csr` -/

/-- The final value of `row_ptr(s)`: one plus the number of entries in rows
before `s`. -/
def rowStart (row : Array ℤ) (nnz s : ℤ) : ℤ := 1 + cntLt row s nnz.toNat

/-- Loop 1: `row_ptr(1:k) = 0`. -/
def Zeroed (row_ptr : Array ℤ) (k : ℕ) : Prop :=
  ∀ j : ℤ, 1 ≤ j → j ≤ k → fval row_ptr j = 0

/-- Loop 2 (counting): after `k` entries, `row_ptr(s+1)` is the number of
entries seen so far in row `s`. -/
def Counted (n : ℤ) (row row_ptr : Array ℤ) (k : ℕ) : Prop :=
  fval row_ptr 1 = 0 ∧ ∀ s : ℤ, 1 ≤ s → s ≤ n → fval row_ptr (s + 1) = cnt row s k

/-- Loop 3 (prefix sum): after `k` steps, `row_ptr(1:k+1)` hold their final
values and `row_ptr(k+2:n+1)` still hold the row counts. -/
def Summed (n nnz : ℤ) (row row_ptr : Array ℤ) (k : ℕ) : Prop :=
  (∀ s : ℤ, 1 ≤ s → s ≤ k + 1 → fval row_ptr s = rowStart row nnz s) ∧
  (∀ s : ℤ, k + 1 ≤ s → s ≤ n → fval row_ptr (s + 1) = cnt row s nnz.toNat)

/-- Loop 4: `next(1:k) = row_ptr(1:k)`. -/
def NextInit (nnz : ℤ) (row next : Array ℤ) (k : ℕ) : Prop :=
  ∀ s : ℤ, 1 ≤ s → s ≤ k → fval next s = rowStart row nnz s

/-- Loop 5 (scatter): after `k` entries, `next(s)` is `row_ptr(s)` plus the
number of entries of row `s` seen so far, and every position already filled
in row `s` holds a valid column index. -/
def Scattered (n nnz : ℤ) (row next col_ind : Array ℤ) (k : ℕ) : Prop :=
  (∀ s : ℤ, 1 ≤ s → s ≤ n → fval next s = rowStart row nnz s + cnt row s k) ∧
  (∀ s : ℤ, 1 ≤ s → s ≤ n → ∀ q : ℤ, rowStart row nnz s ≤ q → q < fval next s →
    1 ≤ fval col_ind q ∧ fval col_ind q ≤ n)

section Coo2csrLemmas
variable {n nnz : ℤ} {row col row_ptr next col_ind : Array ℤ}

theorem rowStart_pos (s : ℤ) : 1 ≤ rowStart row nnz s := by
  have := cntLt_nonneg (row := row) s nnz.toNat
  unfold rowStart; omega

theorem zeroed_init (row_ptr : Array ℤ) : Zeroed row_ptr 0 := fun _ _ _ => by omega

theorem zeroed_step {k : ℕ} {i : ℤ} (h : Zeroed row_ptr k) (hi : i = 1 + k)
    (hs : i ≤ row_ptr.size) : Zeroed (fupd row_ptr i 0) (k + 1) := by
  intro j hj1 hj2
  rw [fval_fupd (by omega) hj1]
  split_ifs
  · rfl
  · exact h j hj1 (by omega)

theorem counted_init {K : ℕ} (h : Zeroed row_ptr K) (hK : n + 1 ≤ K) (hn : 0 ≤ n) :
    Counted n row row_ptr 0 :=
  ⟨h 1 le_rfl (by omega), fun s hs1 hs2 => by rw [h (s + 1) (by omega) (by omega)]; rfl⟩

theorem counted_step {k : ℕ} {i : ℤ} (h : Counted n row row_ptr k) (hcoo : COOPrefix n row col nnz)
    (hi : i = 1 + k) (hin : i ≤ nnz) (hs : (row_ptr.size : ℤ) = n + 1) :
    Counted n row (fupd row_ptr (fval row i + 1) (fval row_ptr (fval row i + 1) + 1)) (k + 1) := by
  obtain ⟨h1, h2⟩ := h
  have hr := hcoo i (by omega) hin
  have hik : i = ((k + 1 : ℕ) : ℤ) := by push_cast; omega
  refine ⟨?_, fun s hs1 hs2 => ?_⟩
  · rw [fval_fupd (by omega) le_rfl, if_neg (by omega), h1]
  · rw [fval_fupd (by omega) (by omega), cnt, ← hik]
    split_ifs with h3 h4 h4
    · rw [h4, h2 s hs1 hs2]
    · omega
    · omega
    · rw [h2 s hs1 hs2]; omega

theorem summed_init {K : ℕ} (h : Counted n row row_ptr K) (hcoo : COOPrefix n row col nnz)
    (hK : (K : ℤ) = nnz) (hs : (row_ptr.size : ℤ) = n + 1) (hn : 0 ≤ n) :
    Summed n nnz row (fupd row_ptr 1 1) 0 := by
  obtain ⟨-, h2⟩ := h
  have hKn : K = nnz.toNat := by omega
  subst hKn
  refine ⟨fun s hs1 hs2 => ?_, fun s hs1 hs2 => ?_⟩
  · obtain rfl : s = 1 := by omega
    rw [fval_fupd (by omega) le_rfl, if_pos rfl, rowStart,
      cntLt_one fun j hj1 hj2 => (hcoo j (by omega) (by omega)).1]
    ring
  · rw [fval_fupd (by omega) (by omega), if_neg (by omega), h2 s (by omega) hs2]

theorem summed_step {k : ℕ} {i : ℤ} (h : Summed n nnz row row_ptr k) (hi : i = 1 + k)
    (hin : i ≤ n) (hs : (row_ptr.size : ℤ) = n + 1) :
    Summed n nnz row (fupd row_ptr (i + 1) (fval row_ptr (i + 1) + fval row_ptr i)) (k + 1) := by
  obtain ⟨h1, h2⟩ := h
  refine ⟨fun s hs1 hs2 => ?_, fun s hs1 hs2 => ?_⟩
  · rw [fval_fupd (by omega) hs1]
    split_ifs with hsi
    · rw [h2 i (by omega) hin, h1 i (by omega) (by omega), hsi, rowStart, rowStart, cntLt_succ]
      ring
    · exact h1 s hs1 (by omega)
  · rw [fval_fupd (by omega) (by omega), if_neg (by omega)]
    exact h2 s (by omega) hs2

theorem Summed.rowPtr_eq {k : ℕ} (h : Summed n nnz row row_ptr k) (hk : n ≤ k) :
    ∀ s, 1 ≤ s → s ≤ n + 1 → fval row_ptr s = rowStart row nnz s :=
  fun s hs1 hs2 => h.1 s hs1 (by omega)

theorem nextInit_init (nnz : ℤ) (row next : Array ℤ) : NextInit nnz row next 0 :=
  fun _ _ _ => by omega

theorem nextInit_step {k K : ℕ} {i : ℤ} (hS : Summed n nnz row row_ptr K) (hK : n ≤ K)
    (h : NextInit nnz row next k) (hi : i = 1 + k) (hin : i ≤ n) (hs : i ≤ next.size) :
    NextInit nnz row (fupd next i (fval row_ptr i)) (k + 1) := by
  intro s hs1 hs2
  rw [fval_fupd (by omega) hs1]
  split_ifs with hsi
  · rw [hsi, hS.rowPtr_eq hK i (by omega) (by omega)]
  · exact h s hs1 (by omega)

theorem scattered_init {K : ℕ} (h : NextInit nnz row next K) (hK : n ≤ K) :
    Scattered n nnz row next col_ind 0 := by
  refine ⟨fun s hs1 hs2 => ?_, fun s hs1 hs2 q hq1 hq2 => ?_⟩
  · rw [h s hs1 (by omega)]; simp [cnt]
  · rw [h s hs1 (by omega)] at hq2; omega

/-- **The key bound**: the scatter position `p = next(row(i))` is in `1..nnz`. -/
theorem scatter_bound {k : ℕ} {i m : ℤ} (h : Scattered n nnz row next col_ind k)
    (hcoo : COOPrefix n row col nnz) (hi : i = 1 + k) (hin : i ≤ nnz) (hm : m = nnz) :
    1 ≤ fval next (fval row i) ∧ fval next (fval row i) ≤ m := by
  subst m
  have hr := hcoo i (by omega) hin
  have hik : i = ((k + 1 : ℕ) : ℤ) := by push_cast; omega
  have e1 := h.1 (fval row i) hr.1 hr.2.1
  have hlt := cnt_lt (row := row) (s := fval row i) (k := k) (K := nnz.toNat) (by omega)
    (by rw [← hik])
  have htop := cntLt_top (row := row) (n := n) (k := nnz.toNat)
    fun j hj1 hj2 => (hcoo j (by omega) (by omega)).2.1
  have hmono := cntLt_mono (row := row) (show fval row i + 1 ≤ n + 1 by omega) nnz.toNat
  have hsucc := cntLt_succ (row := row) (fval row i) nnz.toNat
  have := cntLt_nonneg (row := row) (fval row i) nnz.toNat
  have := cnt_nonneg (row := row) (fval row i) k
  unfold rowStart at e1
  omega

theorem scatter_bound_lo {k : ℕ} {i : ℤ} (h : Scattered n nnz row next col_ind k)
    (hcoo : COOPrefix n row col nnz) (hi : i = 1 + k) (hin : i ≤ nnz) :
    1 ≤ fval next (fval row i) :=
  (scatter_bound h hcoo hi hin rfl).1

theorem scatter_bound_hi {k : ℕ} {i m : ℤ} (h : Scattered n nnz row next col_ind k)
    (hcoo : COOPrefix n row col nnz) (hi : i = 1 + k) (hin : i ≤ nnz) (hm : m = nnz) :
    fval next (fval row i) ≤ m :=
  (scatter_bound h hcoo hi hin hm).2

theorem scattered_step {k : ℕ} {i : ℤ} (h : Scattered n nnz row next col_ind k)
    (hcoo : COOPrefix n row col nnz) (hi : i = 1 + k) (hin : i ≤ nnz)
    (hnx : (next.size : ℤ) = n) (hci : (col_ind.size : ℤ) = nnz) :
    Scattered n nnz row (fupd next (fval row i) (fval next (fval row i) + 1))
      (fupd col_ind (fval next (fval row i)) (fval col i)) (k + 1) := by
  have hb := scatter_bound h hcoo hi hin rfl
  have hr := hcoo i (by omega) hin
  have hik : i = ((k + 1 : ℕ) : ℤ) := by push_cast; omega
  obtain ⟨h1, h2⟩ := h
  refine ⟨fun s hs1 hs2 => ?_, fun s hs1 hs2 q hq1 hq2 => ?_⟩
  · rw [fval_fupd (by omega) hs1, cnt, ← hik]
    split_ifs with h3 h4 h4
    · subst h3; rw [h1 _ hs1 hs2]; ring
    · exact absurd h3.symm h4
    · exact absurd h4.symm h3
    · rw [h1 s hs1 hs2]; ring
  · have hq0 : 1 ≤ q := le_trans (rowStart_pos s) hq1
    rw [fval_fupd (by omega) hq0]
    split_ifs with hq
    · exact ⟨hr.2.2.1, hr.2.2.2⟩
    · apply h2 s hs1 hs2 q hq1
      rw [fval_fupd (by omega) hs1] at hq2
      split_ifs at hq2 with hsr
      · subst hsr; omega
      · exact hq2

/-- At the end of `coo2csr` the arrays form a valid CSR matrix. -/
theorem valid_final {K K' : ℕ} {val : Array ℚ} (hS : Summed n nnz row row_ptr K) (hK : n ≤ K)
    (h : Scattered n nnz row next col_ind K') (hK' : (K' : ℤ) = nnz)
    (hcoo : COOPrefix n row col nnz) (hn : 0 ≤ n)
    (h1 : (row_ptr.size : ℤ) = n + 1) (h2 : (col_ind.size : ℤ) = nnz) (h3 : (val.size : ℤ) = nnz) :
    ValidCSR n nnz row_ptr col_ind val := by
  have hrp := hS.rowPtr_eq hK
  have hK'' : K' = nnz.toNat := by omega
  subst hK''
  have hrow : ∀ j : ℕ, 1 ≤ j → j ≤ nnz.toNat → 1 ≤ fval row j ∧ fval row j ≤ n :=
    fun j hj1 hj2 => ⟨(hcoo j (by omega) (by omega)).1, (hcoo j (by omega) (by omega)).2.1⟩
  refine ⟨hn, h1, h2, h3, ?_, ?_, fun s hs1 hs2 => ?_, fun s hs1 hs2 q hq1 hq2 => ?_⟩
  · rw [hrp 1 le_rfl (by omega), rowStart, cntLt_one fun j hj1 hj2 => (hrow j hj1 hj2).1]; ring
  · rw [hrp (n + 1) (by omega) le_rfl, rowStart, cntLt_top fun j hj1 hj2 => (hrow j hj1 hj2).2]
    omega
  · rw [hrp s hs1 (by omega), hrp (s + 1) (by omega) (by omega), rowStart, rowStart]
    have := cntLt_mono (row := row) (show s ≤ s + 1 by omega) nnz.toNat
    omega
  · rw [hrp s hs1 (by omega)] at hq1
    apply h.2 s hs1 hs2 q hq1
    rw [h.1 s hs1 hs2]
    rw [hrp (s + 1) (by omega) (by omega), rowStart, cntLt_succ] at hq2
    unfold rowStart
    omega

end Coo2csrLemmas

/-- **`coo2csr` never indexes out of bounds** for every valid COO matrix, and
it produces a valid CSR matrix. -/
theorem coo2csr_valid (n nnz : ℤ) (row col : Array ℤ) (val : Array ℚ)
    (hcoo : ValidCOO n nnz row col val) :
    ⦃⌜True⌝⦄ coo2csr n nnz row col val
    ⦃⇓ r => ⌜ValidCSR n nnz r.1 r.2.1 r.2.2⌝⦄ := by
  obtain ⟨hn, hnnz, hsr, hsc, hsv, hpre⟩ := hcoo
  have hrc : ∀ j, 1 ≤ j → j ≤ nnz →
      1 ≤ fval row j ∧ fval row j ≤ n ∧ 1 ≤ fval col j ∧ fval col j ≤ n := hpre
  mvcgen [coo2csr]
  invariants
  · ⇓⟨xs, row_ptr⟩ => ⌜(row_ptr.size : ℤ) = n + 1 ∧ Zeroed row_ptr xs.pos⌝
  · ⇓⟨xs, row_ptr⟩ => ⌜(row_ptr.size : ℤ) = n + 1 ∧ Counted n row row_ptr xs.pos⌝
  · ⇓⟨xs, row_ptr⟩ => ⌜(row_ptr.size : ℤ) = n + 1 ∧ Summed n nnz row row_ptr xs.pos⌝
  · ⇓⟨xs, next⟩ => ⌜(next.size : ℤ) = n ∧ NextInit nnz row next xs.pos⌝
  · ⇓⟨xs, col_ind, csr_val, next, r, p⟩ => ⌜(col_ind.size : ℤ) = nnz ∧
      (csr_val.size : ℤ) = nnz ∧ (next.size : ℤ) = n ∧ Scattered n nnz row next col_ind xs.pos⌝
  all_goals fortran_vcs
  all_goals simp_all (config := { zetaDelta := true }) [falloc]
  all_goals try casesm* _ ∧ _
  all_goals split_conj
  all_goals first
    | omega
    | exact zeroed_init _
    | exact nextInit_init _ _ _
    | (apply zeroed_step <;> vc_side)
    | (apply counted_init <;> vc_side)
    | (apply counted_step <;> vc_side)
    | (apply summed_init <;> vc_side)
    | (apply summed_step <;> vc_side)
    | (apply nextInit_step <;> vc_side)
    | (apply scattered_init <;> vc_side)
    | (apply scatter_bound_lo <;> vc_side)
    | (apply scatter_bound_hi <;> vc_side)
    | (apply scattered_step <;> vc_side)
    | (apply valid_final <;> vc_side)

/-! ## `program sparse` -/

@[spec] theorem tridiag_coo_spec (n : ℤ) :
    ⦃⌜1 ≤ n⌝⦄ tridiag_coo n ⦃⇓ r => ⌜ValidCOO n (3 * n - 2) r.1 r.2.1 r.2.2⌝⦄ := by
  mintro h
  mpure h
  exact tridiag_coo_valid n h

@[spec] theorem coo2csr_spec (n nnz : ℤ) (row col : Array ℤ) (val : Array ℚ) :
    ⦃⌜ValidCOO n nnz row col val⌝⦄ coo2csr n nnz row col val
    ⦃⇓ r => ⌜ValidCSR n nnz r.1 r.2.1 r.2.2⌝⦄ := by
  mintro h
  mpure h
  exact coo2csr_valid n nnz row col val h

@[spec] theorem csr_matvec_spec (n nnz : ℤ) (row_ptr col_ind : Array ℤ) (val x : Array ℚ) :
    ⦃⌜ValidCSR n nnz row_ptr col_ind val ∧ (x.size : ℤ) = n⌝⦄
    csr_matvec n nnz row_ptr col_ind val x ⦃⇓ y => ⌜(y.size : ℤ) = n⌝⦄ := by
  mintro h
  mpure h
  exact csr_matvec_in_bounds n nnz row_ptr col_ind val x h.1 h.2

/-- **`program sparse` never indexes out of bounds**: the only way it can fail
is through one of its `error stop` checks. -/
theorem main_in_bounds :
    ⦃⌜True⌝⦄ main ⦃post⟨fun _ => ⌜True⌝, fun e => ⌜e = .errorStop⌝⟩⦄ := by
  mvcgen [main]
  invariants
  · ⇓⟨xs, x⟩ => ⌜(x.size : ℤ) = 5⌝
  -- the `error stop` checks may throw `errorStop`, so this invariant allows it
  · post⟨fun _ => ⌜True⌝, fun e => ⌜e = .errorStop⌝⟩
  all_goals fortran_vcs

theorem main_no_out_of_bounds : ∀ i, main ≠ .error (.outOfBounds i) :=
  no_out_of_bounds_of_triple main_in_bounds

end Fortran.Sparse
